language: python
python:
  - "3.4"
  - "2.7"
  - "pypy"
  - "3.3"
  - "2.6"
install: pip install pytest inflection SQLAlchemy
# command to run tests, e.g. python setup.py test
script:  python setup.py test
